### ISSUE TITLE
include resource files

### ISSUE THREAD

**Issue by tavojavi** [DrainSmith/PhotoBoothFree#1]
Great project... it will be good if you include the click.png and also StripBackground.png images to see an example.
Had to play around a while to understand why it was failing because strip image was not big enough.

Congrats!

**Comment by DrainSmith** [comment]
Oh, thanks! I added the files to the root of the project. I'll have to actually add them as resources later. The StripBackground.png is intended to be edited to include a graphic for the event. Future versions may generate this automatically or include a way of setting it.

**Comment by tavojavi** [comment]
Thank you!

2016-12-03 13:14 GMT-03:00 DrainSmith <notifications@github.com>:
